### ISSUE TITLE
Crashes with HydroEnergy

### ISSUE THREAD

**Issue by wuggyfoot** [embeddedt/ArchaicFix#51] opened 2022-10-25 10:02 UTC
it's just a big crash in gtnh

https://gist.github.com/wuggyfoot/d7e4eda56a126a829b2eb9b285f2f3cd

**Comment by embeddedt** [comment] 2022-10-25 11:27
Known issue. One of the mods in GTNH assumes the vanilla lighting engine is still in use.

**Comment by makamys** [comment] 2022-10-26 03:06
This is a duplicate of #47.

**Comment by embeddedt** [comment] 2022-10-26 11:21
True, I forgot that we had an issue opened already. Let’s continue in the other issue.

**Closed by embeddedt** 2022-10-26 11:21 UTC
Labels: bug
