### ISSUE TITLE
[0.7.0] Version breaks Botania's Lexicon rendering

### ISSUE THREAD

**Issue by Gronglegrowth** [embeddedt/ArchaicFix#111] opened 2024-01-09 18:47 UTC
Tested this with only ArchaicFix 0.7.0, Botania, and their dependencies, as I noticed this in a large modpack once I updated and wanted to be sure it is ArchaicFix's doing.
Screenshot: 
![Screenshot_20240109_134500](https://github.com/embeddedt/ArchaicFix/assets/32804557/96c4a60f-fb98-4c15-b542-cbf4878a1ecb)

**Comment by SilearFlare** [comment] 2024-01-10 08:01
I've tested this with my own modpack & AF 0.7, and sadly I cannot reproduce the issue. You might want to do a binary check on your mods, or failing that, archaicfix's configs.
![14](https://github.com/embeddedt/ArchaicFix/assets/5557920/a8d3fc19-5cfe-4c43-b81d-d77735504ebe)

**Comment by Gronglegrowth** [comment] 2024-01-10 11:01
This was a test using only Botania, Archaicfix, and their dependencies, on default configs. The cause _is_ Archaicfix, somehow, and I know someone else with a similar issue (except for them, the icons don't render at all, not even squares as I see).

Further, your screenshot shows a list of entries (which does work fine for us), not the main page (which does not).

**Comment by SilearFlare** [comment] 2024-01-10 11:26
Oh my bad, I saw "ender artifacts" and I just opened that one. To be fair the main page renders properly for me as well in the modpack, oddly enough, which should narrow it down at least! :grin: 
In any case I can definitely confirm: empty instance, AF 0.7, default configs, same issue.
![15](https://github.com/embeddedt/ArchaicFix/assets/5557920/db0a816a-cc77-475a-b0cc-20566677877a)
Odd... why is it just working properly in 0.7 in my modpack then? :thinking:
![15](https://github.com/embeddedt/ArchaicFix/assets/5557920/cd83bef3-1d4f-4106-85ce-f26a7433c14f)
It seems that replacing the empty instance's archaicfix config with my modpack's, which worked out of the box, didn't actually do anything. So it's not an AF config issue.
Something *else* in my modpack is fixing the issue? Yes, this is a bit more of a headscratcher than I thought, I apologize.

**Comment by Gronglegrowth** [comment] 2024-01-10 21:51
Hm, do you have any other bugfix/optimizing mods in your modpack, maybe? I wonder if one of them may be fixing it.

**Comment by makamys** [comment] 2024-01-10 23:58
It seems that CoreTweaks's Intel rendering fix (which is on by default) fixes this, I just tested in a minimal instance (with an Nvidia GPU, I should add).

[Here's how the fix is implemented for reference.](https://github.com/makamys/CoreTweaks/blob/7a9ff5d652a856b186fcc7365b01b888899ccd39/src/main/java/makamys/coretweaks/mixin/bugfix/intelcolor/MixinTessellator.java)

**Comment by embeddedt** [comment] 2024-01-11 00:32
If that's the case then ArchaicFix's version of the same fix is probably what causes the problem in the first place.

**Comment by makamys** [comment] 2024-01-11 00:49
Yeah, it doesn't happen with the commit reverted.

**Comment by embeddedt** [comment] 2024-02-15 14:51
This is fixed in 0.7.1.

**Closed by embeddedt** 2024-02-15 14:51 UTC
