### ISSUE TITLE
GregTech 6 crashing on launch.

### ISSUE THREAD

**Issue by Crimento** [embeddedt/ArchaicFix#28] opened 2022-09-08 05:00 UTC
Vanilla 1.7.10 with Forge, FalsePatternLib, MixinBooterLegacy and ArchaicFix only.

Here is the log. Not sure on which side it should be fixed so I opened an issue in both repos
https://github.com/GregTech6/gregtech6/issues/95

https://pastebin.com/PBjqWHQx

**Comment by makamys** [comment] 2022-09-08 05:21
I'm able to reproduce this. Adding [Mixingasm](https://github.com/makamys/Mixingasm) fixes that error, but a different one comes up later instead: 
```
/*     Injection validation failed: Redirector                                                                                                                      */
/*     fasterMatchCheck(Lnet/minecraft/item/crafting/IRecipe;Lnet/minecraft/inventory/InventoryCrafting;Lnet/minecraft/world/World;[Lnet/minecraft/item/ItemStack;) */
/*      in mixins.archaicfix.json:common.gt6.MixinCR expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap mixins.archaicfix.refmap.json      */
/*     [INJECT Applicator Phase -> mixins.archaicfix.json:common.gt6.MixinCR -> Apply Injections ->  -> PostInject ->                                               */
/*     mixins.archaicfix.json:common.gt6.MixinCR->@Redirect::fasterMatchCheck(Lnet/minecraft/item/crafting/IRecipe;Lnet/minecraft/inventory/InventoryCrafting;Lnet/ */
/*     inecraft/world/World;[Lnet/minecraft/item/ItemStack;)Z]                                                    
```

I'm guessing something changed on GT6's side that makes the mixin no longer valid.

**Comment by makamys** [comment] 2022-09-08 05:59
Turns out our mixin was set up wrong. Now I can launch the game without a crash. Mixingasm is still needed though, to work around GT6's ASM transformer being unfriendly to Mixin.

You can try the new build here: https://nightly.link/embeddedt/ArchaicFix/suites/8188325357/artifacts/356244370

**Comment by quentin452** [comment] 2022-09-08 07:11
i tried with gregtech 6 and still crash

**Comment by makamys** [comment] 2022-09-08 07:29
Can you post your `fml-client-latest.log`?

**Comment by quentin452** [comment] 2022-09-08 07:29
ok i will later

**Comment by quentin452** [comment] 2022-09-08 07:32
weird i don't have fml-client-latest.log when i crash

**Comment by quentin452** [comment] 2022-09-08 07:33
crash report :
[crash-2022-09-08_09.32.33-client.txt](https://github.com/embeddedt/ArchaicFix/files/9524692/crash-2022-09-08_09.32.33-client.txt)
crash with codechickencore?

**Comment by makamys** [comment] 2022-09-08 07:42
It looks like you're missing Mixingasm, try adding it.
For the record, the combo that worked for me was:
```
!mixinbooterlegacy-1.1.2.jar
archaicfix-mc1.7.10-0.3.0-14-g9907035.jar
falsepatternlib-mc1.7.10-0.10.10.jar
gregtech_1.7.10-6.15.03.jar
mixingasm-1.7.10-0.2.2.jar
```

**Comment by quentin452** [comment] 2022-09-08 07:51
Actually this crash can't be solved by you because the crash happens between forgemultipart and gregtech 6

**Comment by Crimento** [comment] 2022-09-08 07:55
> You can try the new build here

Tried it with mixingasm and latest build and it works, thank you! Is there something that could be done on Greg's side?

**Comment by quentin452** [comment] 2022-09-08 08:14
> > You can try the new build here
> 
> Tried it with mixingasm and latest build and it works, thank you! Is there something that could be done on Greg's side?

what are you talking about ? for the greg side?

**Comment by makamys** [comment] 2022-09-08 08:36
> Is there something that could be done on Greg's side?

Well, the issue seems to happen because GT's transformer loads extra classes while it runs, and Mixin doesn't like that. The proper fix would be to avoid the class loading. I'm not sure if it would work here, but one trick to accomplish this is to use `Class#getResource` to get the raw class bytes and parse that, instead of asking the class loader to load the class.

The "lazy" fix would be to do what Mixingasm does and add GT6's transformer as an exception using `MixinEnvironment.getCurrentEnvironment().addTransformerExclusion()`. This has the downside that mixins won't be able to target the GT6-transformed versions of classes.

**Comment by makamys** [comment] 2022-09-08 08:42
Setting `transformer:gregtech.asm.transformers.Minecraft_MinecraftServerIntegratedLaunchMainMenuPartialFix = false` in GT6's `asm.ini` avoids the crash, confirming it's the only misbehaving transformer. This also acts as an alternative workaround (this one has the downside that you miss out on the bug fix the transformer is meant to provide).

**Comment by embeddedt** [comment] 2022-09-08 13:45
Thanks for the fix @makamys.

Regarding that transformer being disabled, I'm pretty sure Greg mentioned that that bugfix doesn't work entirely reliably, and I have been trying to implement a better one on my side for quite some time, so I doubt it will affect much to keep it off.

**Comment by makamys** [comment] 2022-09-08 19:37
> I have been trying to implement a better one on my side for quite some time

Are you talking about `fixLoginRaceCondition`?

**Comment by GregoriusT** [comment] 2022-09-13 06:40
Not sure what yours does, but I did attempt to fix the whole thing, where you get kicked back to the main menu TWICE in a row sometimes, and only the third time you actually load a Singleplayer World, but at the cost of having a Minecraft "Server" instance running in the background forever that you need to Task Kill manually afterwards.

I am not sure how well my fix works, it probably only reduced the amount of times it happens, because I am still getting that Bug from time to time...

**Comment by embeddedt** [comment] 2022-11-06 23:09
I'm closing this as I think the original issue is solved and I don't have time to investigate the race condition problem further at the moment.

**Closed by embeddedt** 2022-11-06 23:09 UTC
